server:
  tomcat:
    accesslog:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost/lend_a_book?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.sendgrid.net
    port: 25
    username: apikey
    password: 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

logging:
  level:
    lk:
      digitallibrary: DEBUG
    root: INFO

